# Generated by Django 2.2.2 on 2021-04-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hand',
            new_name='head',
        ),
    ]
